name: replicache
description: Flutter Bindings for the Replicache Database
version: 0.0.0+dev
author: Rocicorp
homepage: https://replicache.dev

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0+4

flutter:
  plugin:
    androidPackage: roci.dev.replicache
    pluginClass: ReplicachePlugin
