name: redo
description: An offline-first todo app using Replicache!

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: 0.5.6+3
  http: ^0.12.0+4

  # To run the sample, first run /replicache-sdk-flutter/build.sh once
  replicache:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
